
project_id = "ftcjcvyyecypjvjhrqxq"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false

[vector]
enabled = false

# Configure the send-invitations function
[functions.send-invitations]
verify_jwt = true

# Environment variables for SMTP email sending
[functions.send-invitations.env]
SMTP_HOST = "placeholder"
SMTP_PORT = "587"
SMTP_USERNAME = "placeholder"
SMTP_PASSWORD = "placeholder"
SMTP_CRYPTO = "tls"
PUBLIC_APP_URL = "placeholder"

# Environment variables for EmailJS fallback (optional)
EMAILJS_SERVICE_ID = "placeholder"
EMAILJS_TEMPLATE_ID = "placeholder"
EMAILJS_USER_ID = "placeholder"

